name: Publish New Release

on:
  pull_request:
    branch:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: 1.10.0
          release_name: 1.10.0
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build-mac:
    runs-on: macos-latest
    needs: release
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
      - run: npm install yarn
      - run: yarn install
      - run: yarn run release
      - run: tar -zcf dbm-mac.tar.gz ./release/mac/dbm.app

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dbm-mac.tar.gz
          asset_name: dbm-mac.tar.gz
          asset_content_type: application/x-tg

  build-win:
    runs-on: windows-latest
    needs: release
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
      - run: npm install yarn
      - run: yarn install
      - run: yarn run build:win
      - run: tar -cvf dbm-win.tar.gz ./release/dbm*.exe

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dbm-win.tar.gz
          asset_name: dbm-win.tar.gz
          asset_content_type: application/x-tg
