name: Publish New Release

on:
  pull_request:
    branch:
      - 'master'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:

    # Step 1: download the source code (pull the code from CI / CD to your local)
    - name: Checkout
      uses: actions/checkout@master

    # Step 2: package and build
    - name: Build
      uses: actions/setup-node@master
    - run: npm install yarn
    - run: yarn install
    - run: yarn run build
    - run: tar -zcf dbm-mac.tar.gz ./build/mac/dbm.app

    # Step 3: release
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: 1.4.0
        release_name: 1.4.0
        draft: false
        prerelease: false

    # Step 4: upload the build result to release (upload the packaged tgz to release)
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dbm-mac.tar.gz
        asset_name: dbm-mac.tar.gz
        asset_content_type: application/x-tg
